Repository NHN-YesAladin/yesaladin_shop, pull requests merged in 2023-01, with the labels that each got.

#5 Feat: 카테고리 entity 맵핑
  .gitignore
  src/main/java/shop/yesaladin/shop/category/controller/CategoryController.java
  src/main/java/shop/yesaladin/shop/category/domain/model/Category.java
  src/main/java/shop/yesaladin/shop/category/exception/CategoryNotFoundException.java
  src/main/java/shop/yesaladin/shop/category/persistence/JpaCategoryRepository.java
  src/test/java/shop/yesaladin/shop/category/persistence/JpaCategoryRepositoryTest.java
Labels: Enhancement[기능추가 또는 향상]

#34 Feature/#17
  pom.xml
  src/main/java/shop/yesaladin/shop/order/domain/model/OrderProduct.java
  src/main/java/shop/yesaladin/shop/payment/domain/model/Payment.java
  src/main/java/shop/yesaladin/shop/payment/domain/model/PaymentCancel.java
  src/main/java/shop/yesaladin/shop/payment/domain/model/PaymentCard.java
  src/main/java/shop/yesaladin/shop/payment/domain/model/PaymentCode.java
  src/main/java/shop/yesaladin/shop/payment/persistence/converter/PaymentCodeConverter.java
  src/main/java/shop/yesaladin/shop/review/domain/model/Review.java
  src/main/java/shop/yesaladin/shop/review/domain/model/ReviewImage.java
Labels: Enhancement[기능추가 또는 향상]

#50 Hotfix: bug 수정
  src/main/java/shop/yesaladin/shop/member/domain/repository/QueryMemberGradeHistoryRepository.java
  src/main/java/shop/yesaladin/shop/member/persistence/JpaMemberGradeHistoryRepository.java
  src/test/java/shop/yesaladin/shop/member/persistence/JpaMemberGradeHistoryRepositoryTest.java
  src/test/java/shop/yesaladin/shop/member/persistence/JpaMemberGradeRepositoryTest.java
  src/test/java/shop/yesaladin/shop/member/persistence/JpaRoleRepositoryTest.java
Labels: Bug[버그]

#62 [Test] Test refactoring 및 javadoc 작성
  src/main/java/shop/yesaladin/shop/member/domain/model/MemberRole.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/CommandMemberGradeHistoryRepository.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/CommandMemberGradeRepository.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/CommandMemberRepository.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/CommandMemberRoleRepository.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/CommandRoleRepository.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/QueryMemberGradeHistoryRepository.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/QueryMemberGradeRepository.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/QueryMemberRepository.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/QueryMemberRoleRepository.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/QueryRoleRepository.java
  src/test/java/shop/yesaladin/shop/member/dummy/RoleDummy.java
  src/test/java/shop/yesaladin/shop/member/persistence/JpaMemberGradeHistoryRepositoryTest.java
  src/test/java/shop/yesaladin/shop/member/persistence/JpaMemberGradeRepositoryTest.java
  src/test/java/shop/yesaladin/shop/member/persistence/JpaMemberRepositoryTest.java
  src/test/java/shop/yesaladin/shop/member/persistence/JpaMemberRoleRepositoryTest.java
  src/test/java/shop/yesaladin/shop/member/persistence/JpaRoleRepositoryTest.java
Labels: Documentation[문서], Test[테스트]

#65 Feature/#35 signup
  src/main/java/shop/yesaladin/shop/member/controller/MemberController.java
  src/main/java/shop/yesaladin/shop/member/domain/model/Member.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/QueryMemberRepository.java
  src/main/java/shop/yesaladin/shop/member/dto/MemberCreateRequest.java
  src/main/java/shop/yesaladin/shop/member/dto/MemberCreateResponse.java
  src/main/java/shop/yesaladin/shop/member/exception/MemberGradeNotFoundException.java
  src/main/java/shop/yesaladin/shop/member/exception/MemberNotFoundException.java
  src/main/java/shop/yesaladin/shop/member/exception/MemberProfileAlreadyExistException.java
  src/main/java/shop/yesaladin/shop/member/service/impl/CommandMemberServiceImpl.java
  src/main/java/shop/yesaladin/shop/member/service/impl/QueryMemberGradeServiceImpl.java
  src/main/java/shop/yesaladin/shop/member/service/impl/QueryMemberServiceImpl.java
  src/main/java/shop/yesaladin/shop/member/service/inter/CommandMemberService.java
  src/main/java/shop/yesaladin/shop/member/service/inter/QueryMemberGradeService.java
  src/main/java/shop/yesaladin/shop/member/service/inter/QueryMemberService.java
  src/test/java/shop/yesaladin/shop/member/controller/MemberControllerTest.java
  src/test/java/shop/yesaladin/shop/member/service/impl/CommandMemberServiceImplTest.java
  src/test/java/shop/yesaladin/shop/member/service/impl/QueryMemberGradeServiceImplTest.java
Labels: Enhancement[기능추가 또는 향상], Test[테스트]

#67 Feature/#66 member
  src/main/java/shop/yesaladin/shop/member/exception/MemberNotFoundException.java
  src/main/java/shop/yesaladin/shop/member/service/impl/QueryMemberServiceImpl.java
  src/main/java/shop/yesaladin/shop/member/service/inter/QueryMemberService.java
  src/test/java/shop/yesaladin/shop/member/service/impl/QueryMemberServiceImplTest.java
Labels: Enhancement[기능추가 또는 향상], Test[테스트]

#72 Fix: CommandService의 일부 return 값을 entity가 아닌 dto로 변경
  src/main/java/shop/yesaladin/shop/member/controller/CommandMemberController.java
  src/main/java/shop/yesaladin/shop/member/domain/model/MemberRole.java
  src/main/java/shop/yesaladin/shop/member/dto/MemberCreateResponse.java
  src/main/java/shop/yesaladin/shop/member/service/impl/CommandMemberServiceImpl.java
  src/main/java/shop/yesaladin/shop/member/service/impl/QueryMemberGradeServiceImpl.java
  src/main/java/shop/yesaladin/shop/member/service/impl/QueryMemberServiceImpl.java
  src/main/java/shop/yesaladin/shop/member/service/inter/CommandMemberService.java
  src/main/java/shop/yesaladin/shop/member/service/inter/QueryMemberGradeService.java
  src/main/java/shop/yesaladin/shop/member/service/inter/QueryMemberService.java
  src/test/java/shop/yesaladin/shop/member/controller/CommandMemberControllerTest.java
  src/test/java/shop/yesaladin/shop/member/service/impl/CommandMemberServiceImplTest.java
Labels: Bug[버그]

#78 Fix: member entity에 phone column 추가
  src/main/java/shop/yesaladin/shop/member/domain/model/Member.java
  src/main/java/shop/yesaladin/shop/member/dto/MemberCreateRequest.java
  src/test/java/shop/yesaladin/shop/member/controller/CommandMemberControllerTest.java
  src/test/java/shop/yesaladin/shop/member/dummy/MemberDummy.java
  src/test/java/shop/yesaladin/shop/order/persistence/dummy/DummyMember.java
Labels: Bug[버그]

#98 Feature/#88 카테고리depth추가 생성 수정 변경
  src/main/java/shop/yesaladin/shop/category/controller/CommandCategoryController.java
  src/main/java/shop/yesaladin/shop/category/controller/QueryCategoryController.java
  src/main/java/shop/yesaladin/shop/category/domain/model/Category.java
  src/main/java/shop/yesaladin/shop/category/domain/model/ProductCategory.java
  src/main/java/shop/yesaladin/shop/category/domain/repository/QueryCategoryRepository.java
  src/main/java/shop/yesaladin/shop/category/domain/repository/QueryComplexCategoryRepository.java
  src/main/java/shop/yesaladin/shop/category/domain/repository/QueryProductCategoryRepository.java
  src/main/java/shop/yesaladin/shop/category/domain/repository/impl/QueryComplexCategoryRepositoryImpl.java
  src/main/java/shop/yesaladin/shop/category/dto/CategoryOnlyIdDto.java
  src/main/java/shop/yesaladin/shop/category/dto/CategoryRequestDto.java
  src/main/java/shop/yesaladin/shop/category/dto/CategoryResponseDto.java
  src/main/java/shop/yesaladin/shop/category/dto/ResultCodeDto.java
  src/main/java/shop/yesaladin/shop/category/service/impl/CommandCategoryServiceImpl.java
  src/main/java/shop/yesaladin/shop/category/service/impl/QueryCategoryServiceImpl.java
  src/main/java/shop/yesaladin/shop/category/service/inter/CommandCategoryService.java
  src/main/java/shop/yesaladin/shop/category/service/inter/QueryCategoryService.java
  src/test/java/shop/yesaladin/shop/category/controller/CommandCategoryControllerTest.java
  src/test/java/shop/yesaladin/shop/category/controller/QueryCategoryControllerTest.java
  src/test/java/shop/yesaladin/shop/category/domain/model/CategoryTest.java
  src/test/java/shop/yesaladin/shop/category/domain/repository/impl/QueryComplexCategoryRepositoryImplTest.java
  src/test/java/shop/yesaladin/shop/category/dummy/CategoryDummy.java
  src/test/java/shop/yesaladin/shop/category/persistence/JpaCategoryRepositoryTest.java
  src/test/java/shop/yesaladin/shop/category/persistence/JpaProductCategoryRepositoryTest.java
  src/test/java/shop/yesaladin/shop/category/service/inter/CommandCategoryServiceTest.java
  src/test/java/shop/yesaladin/shop/category/service/inter/QueryCategoryServiceTest.java
Labels: Bug[버그]

#114 Feature/#89 member fix
  src/main/java/shop/yesaladin/shop/common/advice/ControllerAdvice.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/QueryMemberRepository.java
  src/main/java/shop/yesaladin/shop/member/dto/MemberCreateResponseDto.java
  src/main/java/shop/yesaladin/shop/member/exception/MemberRoleNotFoundException.java
  src/main/java/shop/yesaladin/shop/member/service/impl/CommandMemberServiceImpl.java
  src/test/java/shop/yesaladin/shop/member/persistence/JpaMemberRepositoryTest.java
  src/test/java/shop/yesaladin/shop/member/service/impl/CommandMemberServiceImplTest.java
Labels: Documentation[문서], Enhancement[기능추가 또는 향상], Test[테스트]

#117 Fix: exists method bug fix
  src/main/java/shop/yesaladin/shop/member/domain/repository/QueryMemberRepository.java
  src/main/java/shop/yesaladin/shop/member/service/impl/CommandMemberServiceImpl.java
  src/test/java/shop/yesaladin/shop/member/persistence/JpaMemberRepositoryTest.java
  src/test/java/shop/yesaladin/shop/member/service/impl/CommandMemberServiceImplTest.java
Labels: Bug[버그]

#147 BDDMockito에서 Mockito로 변경
  src/test/java/shop/yesaladin/shop/member/controller/CommandMemberControllerTest.java
Labels: Test[테스트]

#176 [Feat] : MemberCoupon_OrderUsedCoupon
  src/main/java/shop/yesaladin/shop/member/domain/model/MemberCoupon.java
  src/main/java/shop/yesaladin/shop/order/domain/dummy/CouponIssuance.java
  src/main/java/shop/yesaladin/shop/order/domain/model/OrderUsedCoupon.java
  src/main/java/shop/yesaladin/shop/payment/persistence/converter/PaymentCodeConverter.java
  src/main/java/shop/yesaladin/shop/review/domain/model/Review.java
  src/main/resources/application.yml
  src/test/java/shop/yesaladin/shop/order/persistence/JpaOrderUsedCouponRepositoryTest.java
  src/test/java/shop/yesaladin/shop/order/persistence/dummy/DummyCouponIssuance.java
  src/test/java/shop/yesaladin/shop/order/persistence/dummy/DummyOrderUsedCoupon.java
Labels: Enhancement[기능추가 또는 향상]

#179 Feature/#159 카테고리 리팩토링
  src/main/asciidoc/category-api-docs.adoc
  src/main/java/shop/yesaladin/shop/category/controller/CommandCategoryController.java
  src/main/java/shop/yesaladin/shop/category/controller/QueryCategoryController.java
  src/main/java/shop/yesaladin/shop/category/domain/model/Category.java
  src/main/java/shop/yesaladin/shop/category/domain/model/ProductCategory.java
  src/main/java/shop/yesaladin/shop/category/domain/repository/QueryCategoryRepository.java
  src/main/java/shop/yesaladin/shop/category/dto/CategoriesSimpleResponseDto.java
  src/main/java/shop/yesaladin/shop/category/dto/CategoryRequestDto.java
  src/main/java/shop/yesaladin/shop/category/dto/CategoryResponseDto.java
  src/main/java/shop/yesaladin/shop/category/dto/CategorySimpleDto.java
  src/main/java/shop/yesaladin/shop/category/exception/ProductCategoryNotFoundException.java
  src/main/java/shop/yesaladin/shop/category/persistence/JpaCommandCategoryRepository.java
  src/main/java/shop/yesaladin/shop/category/persistence/QueryDslCategoryRepositoryImpl.java
  src/main/java/shop/yesaladin/shop/category/service/impl/CommandCategoryServiceImpl.java
  src/main/java/shop/yesaladin/shop/category/service/impl/QueryCategoryServiceImpl.java
  src/main/java/shop/yesaladin/shop/category/service/inter/CommandCategoryService.java
  src/main/java/shop/yesaladin/shop/category/service/inter/QueryCategoryService.java
  src/test/java/shop/yesaladin/shop/category/controller/CommandCategoryControllerTest.java
  src/test/java/shop/yesaladin/shop/category/controller/QueryCategoryControllerTest.java
  src/test/java/shop/yesaladin/shop/category/domain/model/CategoryTest.java
  src/test/java/shop/yesaladin/shop/category/persistence/JpaCommandCategoryRepositoryTest.java
  src/test/java/shop/yesaladin/shop/category/persistence/JpaProductCategoryRepositoryTest.java
  src/test/java/shop/yesaladin/shop/category/persistence/QueryDslCategoryRepositoryImplTest.java
  src/test/java/shop/yesaladin/shop/category/service/inter/CommandCategoryServiceTest.java
  src/test/java/shop/yesaladin/shop/category/service/inter/QueryCategoryServiceTest.java
  src/test/java/shop/yesaladin/shop/order/persistence/JpaOrderUsedCouponRepositoryTest.java
Labels: Documentation[문서], Enhancement[기능추가 또는 향상], Test[테스트]

#255 Fix/#253 카테고리 수정사항 반영 - CORS 구현 및 rest docs 작성
  src/main/asciidoc/category-api-docs.adoc
  src/main/asciidoc/payment-api-docs.adoc
  src/main/java/shop/yesaladin/shop/category/controller/QueryCategoryController.java
  src/test/java/shop/yesaladin/shop/category/controller/QueryCategoryControllerTest.java
Labels: Bug[버그]

#284 Fix: 회원 탈퇴 API 수정
  src/main/java/shop/yesaladin/shop/member/controller/CommandMemberController.java
  src/main/java/shop/yesaladin/shop/member/dto/MemberWithdrawRequestDto.java
  src/test/java/shop/yesaladin/shop/member/controller/CommandMemberControllerTest.java
Labels: Bug[버그]

#308 Docs: javadoc 수정 및 추가
  src/main/java/shop/yesaladin/shop/member/controller/CommandMemberController.java
  src/main/java/shop/yesaladin/shop/member/controller/QueryMemberController.java
  src/main/java/shop/yesaladin/shop/member/controller/QueryMemberLoginController.java
  src/main/java/shop/yesaladin/shop/member/domain/model/Member.java
  src/main/java/shop/yesaladin/shop/member/domain/model/MemberGenderCode.java
  src/main/java/shop/yesaladin/shop/member/domain/model/MemberGrade.java
  src/main/java/shop/yesaladin/shop/member/domain/model/MemberGradeHistory.java
  src/main/java/shop/yesaladin/shop/member/domain/model/MemberRole.java
  src/main/java/shop/yesaladin/shop/member/domain/model/Role.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/CommandMemberGradeHistoryRepository.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/CommandMemberRepository.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/CommandMemberRoleRepository.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/CommandRoleRepository.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/QueryMemberGradeHistoryRepository.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/QueryMemberRepository.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/QueryMemberRoleRepository.java
  src/main/java/shop/yesaladin/shop/member/domain/repository/QueryRoleRepository.java
  src/main/java/shop/yesaladin/shop/member/dto/MemberCreateRequestDto.java
  src/main/java/shop/yesaladin/shop/member/dto/MemberCreateResponseDto.java
  src/main/java/shop/yesaladin/shop/member/dto/MemberLoginResponseDto.java
  src/main/java/shop/yesaladin/shop/member/dto/MemberProfileExistResponseDto.java
  src/main/java/shop/yesaladin/shop/member/dto/MemberWithdrawResponseDto.java
  src/main/java/shop/yesaladin/shop/member/exception/MemberGradeNotFoundException.java
  src/main/java/shop/yesaladin/shop/member/exception/MemberNotFoundException.java
  src/main/java/shop/yesaladin/shop/member/exception/MemberProfileAlreadyExistException.java
  src/main/java/shop/yesaladin/shop/member/exception/MemberRoleNotFoundException.java
  src/main/java/shop/yesaladin/shop/member/persistence/JpaCommandMemberGradeHistoryRepository.java
  src/main/java/shop/yesaladin/shop/member/persistence/JpaCommandMemberRoleRepository.java
  src/main/java/shop/yesaladin/shop/member/persistence/JpaMemberRepository.java
  src/main/java/shop/yesaladin/shop/member/persistence/JpaRoleRepository.java
  src/main/java/shop/yesaladin/shop/member/persistence/QueryDslQueryMemberRoleRepository.java
  src/main/java/shop/yesaladin/shop/member/persistence/converter/MemberGenderCodeConverter.java
  src/main/java/shop/yesaladin/shop/member/persistence/converter/MemberGradeCodeConverter.java
  src/main/java/shop/yesaladin/shop/member/service/impl/CommandMemberServiceImpl.java
  src/main/java/shop/yesaladin/shop/member/service/impl/QueryMemberServiceImpl.java
  src/main/java/shop/yesaladin/shop/member/service/inter/CommandMemberService.java
  src/main/java/shop/yesaladin/shop/member/service/inter/QueryMemberGradeService.java
  src/main/java/shop/yesaladin/shop/member/service/inter/QueryMemberService.java
Labels: Documentation[문서]
