Repository NHN-YesAladin/yesaladin_shop, pull requests merged in 2023-02, with the labels that each got.

#343 Fix: 상품, 연관관계 잘못된 페이징 코드 수정
  src/main/java/shop/yesaladin/shop/product/persistence/QueryDslProductRepository.java
  src/main/java/shop/yesaladin/shop/product/persistence/QueryDslRelationRepository.java
Labels: Bug[버그]

#373 Feature/OAuth2
  src/main/java/shop/yesaladin/shop/member/controller/QueryMemberLoginController.java
  src/main/java/shop/yesaladin/shop/member/service/impl/QueryMemberServiceImpl.java
  src/main/java/shop/yesaladin/shop/member/service/inter/QueryMemberService.java
  src/test/java/shop/yesaladin/shop/member/controller/QueryMemberLoginControllerTest.java
  src/test/java/shop/yesaladin/shop/member/service/impl/QueryMemberServiceImplTest.java
Labels: Documentation[문서], Enhancement[기능추가 또는 향상], Test[테스트]

#391 Feat: ISBN으로 상품 제목 조회 구현 및 테스트 작성
  src/main/java/shop/yesaladin/shop/product/controller/CommandProductController.java
  src/main/java/shop/yesaladin/shop/product/controller/CommandRelationController.java
  src/main/java/shop/yesaladin/shop/product/controller/QueryProductController.java
  src/main/java/shop/yesaladin/shop/product/controller/QueryProductTypeController.java
  src/main/java/shop/yesaladin/shop/product/controller/QueryRelationController.java
  src/main/java/shop/yesaladin/shop/product/controller/SearchProductController.java
  src/main/java/shop/yesaladin/shop/product/domain/model/Product.java
  src/main/java/shop/yesaladin/shop/product/domain/model/Relation.java
  src/main/java/shop/yesaladin/shop/product/domain/model/SearchedProduct.java
  src/main/java/shop/yesaladin/shop/product/domain/model/SearchedProductFile.java
  src/main/java/shop/yesaladin/shop/product/domain/model/SubscribeProduct.java
  src/main/java/shop/yesaladin/shop/product/domain/model/TotalDiscountRate.java
  src/main/java/shop/yesaladin/shop/product/domain/repository/QueryProductRepository.java
  src/main/java/shop/yesaladin/shop/product/domain/repository/QuerySubscribeProductRepository.java
  src/main/java/shop/yesaladin/shop/product/domain/repository/QueryTotalDiscountRateRepository.java
  src/main/java/shop/yesaladin/shop/product/domain/repository/SearchProductRepository.java
  src/main/java/shop/yesaladin/shop/product/dto/ProductCreateDto.java
  src/main/java/shop/yesaladin/shop/product/dto/ProductDetailResponseDto.java
  src/main/java/shop/yesaladin/shop/product/dto/ProductModifyDto.java
  src/main/java/shop/yesaladin/shop/product/dto/ProductOnlyTitleDto.java
  src/main/java/shop/yesaladin/shop/product/dto/ProductOrderRequestDto.java
  src/main/java/shop/yesaladin/shop/product/dto/ProductUpdateDto.java
  src/main/java/shop/yesaladin/shop/product/dto/ProductsResponseDto.java
  src/main/java/shop/yesaladin/shop/product/dto/RelationCreateDto.java
  src/main/java/shop/yesaladin/shop/product/dto/RelationResponseDto.java
  src/main/java/shop/yesaladin/shop/product/dto/RelationsResponseDto.java
  src/main/java/shop/yesaladin/shop/product/dto/SearchProductPageRequestDto.java
  src/main/java/shop/yesaladin/shop/product/dto/SearchedProductDto.java
  src/main/java/shop/yesaladin/shop/product/dto/SearchedProductManagerDto.java
  src/main/java/shop/yesaladin/shop/product/dto/SearchedProductManagerResponseDto.java
  src/main/java/shop/yesaladin/shop/product/dto/SearchedProductResponseDto.java
  src/main/java/shop/yesaladin/shop/product/exception/ProductNotFoundException.java
  src/main/java/shop/yesaladin/shop/product/persistence/ElasticProductRepository.java
  src/main/java/shop/yesaladin/shop/product/persistence/QueryDslProductRepository.java
  src/main/java/shop/yesaladin/shop/product/persistence/QueryDslRelationRepository.java
  src/main/java/shop/yesaladin/shop/product/persistence/converter/ProductSavingMethodCodeConverter.java
  src/main/java/shop/yesaladin/shop/product/persistence/converter/ProductTypeCodeConverter.java
  src/main/java/shop/yesaladin/shop/product/service/impl/CommandProductServiceImpl.java
  src/main/java/shop/yesaladin/shop/product/service/impl/QueryProductServiceImpl.java
  src/main/java/shop/yesaladin/shop/product/service/impl/QueryProductTypeServiceImpl.java
  src/main/java/shop/yesaladin/shop/product/service/impl/QueryRelationServiceImpl.java
  src/main/java/shop/yesaladin/shop/product/service/inter/CommandProductService.java
  src/main/java/shop/yesaladin/shop/product/service/inter/QueryProductService.java
  src/main/java/shop/yesaladin/shop/product/service/inter/QueryProductTypeService.java
  src/test/java/shop/yesaladin/shop/product/controller/QueryProductControllerTest.java
  src/test/java/shop/yesaladin/shop/product/persistence/QueryDslProductRepositoryTest.java
  src/test/java/shop/yesaladin/shop/product/service/impl/QueryProductServiceImplTest.java
Labels: Enhancement[기능추가 또는 향상]

#554 Docs: member 관련 REST Docs 추가
  src/main/asciidoc/member-api-docs.adoc
  src/main/asciidoc/member-login-api-docs.adoc
  src/main/asciidoc/member-signup-api-docs.adoc
  src/main/java/shop/yesaladin/shop/member/service/impl/QueryMemberServiceImpl.java
  src/main/java/shop/yesaladin/shop/member/service/inter/QueryMemberService.java
  src/test/java/shop/yesaladin/shop/member/controller/QueryMemberLoginControllerTest.java
  src/test/java/shop/yesaladin/shop/member/service/impl/QueryMemberServiceImplTest.java
Labels: Documentation[문서]
